---
- hosts: localhost #, fedora, ubuntu
  tasks:
  - name: Get Gpu
    get_gpu:
    register: gpu

  - debug:
      msg: "Hello {{gpu}}"

  - debug:
      msg: |
        Intel GPU
        discrete: {{ gpu.hw.intel.discrete }}
        integrated: {{ gpu.hw.intel.integrated }}
